### ISSUE TITLE
Differentiate byte strings and text strings

### ISSUE THREAD

**Issue by geonnave** [scalpel-software/cbor#1]
As per RFC 7049, there are two types for string-like objects:

- byte string (initial bytes from 0x40 to 0x5f)
- text string (initial bytes from 0x60 to 0x7f)

I was able to generate text strings with CBOR.encode, but I could not generate byte strings. Any ideas?

In my particular use case, I am encoding a digital signature as part of a CBOR message:

```elixir
iex(39)> sig
<<163, 123, 73, 53, 241, 26, 53, 147, 219, 117, 91, 170, 239, 198, 167, 21, 246,
  117, 186, 249, 230, 246, 246, 125, 162, 151, 118, 125, 104, 118, 241, 203,
  141, 95, 89, 146, 46, 181, 160, 77, 216, 199, 225, 150, 225, 248, 153, 125,
  13, 254, ...>>
iex(40)> sig |> CBOR.encode() |> Base.encode16()
"7840A37B4935F11A3593DB755BAAEFC6A715F675BAF9E6F6F67DA297767D6876F1CB8D5F59922EB5A04DD8C7E196E1F8997D0DFE7337FBB7C3AC22C86B6092E93901"
```

When loading the hexadecimal into a Python CBOR library, it fails, since it is expecting a printable text string (initial byte is 0x78).
```python
>>> import cbor2
>>> cbor2.loads(bytes.fromhex("7840A37B4935F11A3593DB755BAAEFC6A715F675BAF9E6F6F67DA297767D6876F1CB8D5F59922EB5A04DD8C7E196E1F8997D0DFE7337FBB7C3AC22C86B6092E93901"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte
```

So it would be useful if the library allowed encoding of binary objects as CBOR byte strings.

**Comment by geonnave** [comment]
I just learned that I have to use a CBOR.Tag to encode bytes, and it worked. Closing the issue.

**Comment by tomciopp** [comment]
Ah, was just about to respond. Yeah you have to wrap the sig like this `%CBOR.Tag{tag: :bytes, value: sig}` and it should do what you want.

If you ever need to understand what to encode/decode take a look at the tests for the library. They should follow the exact examples in Appendix A of the RFC.
